-- ===== Таблиця БезпечнеСередовище =====
CREATE TABLE SAFEENVIRONMENT (
    SEC_ID INTEGER PRIMARY KEY,
    SECURITY_LEVEL VARCHAR(30) NOT NULL CHECK (
        SECURITY_LEVEL IN ('Базовий', 'Розширений', 'Максимальний')
    ),
    CORRECTNESS_CHECK BOOLEAN NOT NULL DEFAULT TRUE,
    AUTO_SAVE BOOLEAN NOT NULL DEFAULT TRUE
);

-- ===== Таблиця Користувач =====
CREATE TABLE SYSTEMUSER (
    USER_ID INTEGER PRIMARY KEY,
    SEC_ID INTEGER NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL CHECK (
        USER_NAME ~ '^[A-ЯІЇЄҐA-Za-z]{2,50}$'
    ),
    AGE INTEGER NOT NULL CHECK (AGE > 0),
    WORKLOAD VARCHAR(30) NOT NULL CHECK (
        WORKLOAD IN ('Низьке', 'Середнє', 'Високе')
    ),
    WORKING_HOURS INTEGER CHECK (WORKING_HOURS >= 0),
    LEVEL_OF_EXPERIENCE VARCHAR(30) DEFAULT 'Початківець' CHECK (
        LEVEL_OF_EXPERIENCE IN ('Початківець', 'Середній', 'Експерт')
    ),
    CONSTRAINT FK_USER_SECURITY FOREIGN KEY (
        SEC_ID
    ) REFERENCES SAFEENVIRONMENT (SEC_ID)
);

-- ===== Таблиця Скульптура =====
CREATE TABLE SCULPTURE (
    SCULPTURE_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    SEC_ID INTEGER NOT NULL,
    SCULPTURE_NAME VARCHAR(100) NOT NULL CHECK (
        SCULPTURE_NAME ~ '^[A-Za-zА-Яа-я0-9\s-]{2,100}$'
    ),
    MATERIAL VARCHAR(50) CHECK (
        MATERIAL IN ('Глина', 'Гіпс', 'Камінь', 'Метал')
    ),
    SIZE VARCHAR(30) CHECK (SIZE IN ('Малий', 'Середній', 'Великий')),
    CREATION_DATE DATE NOT NULL,
    CONSTRAINT FK_SCULPTURE_USER FOREIGN KEY (USER_ID) REFERENCES SYSTEMUSER (
        USER_ID
    ),
    CONSTRAINT FK_SCULPTURE_SECURITY FOREIGN KEY (
        SEC_ID
    ) REFERENCES SAFEENVIRONMENT (SEC_ID)
);

-- ===== Таблиця ІнструментРедагування =====
CREATE TABLE EDITINGTOOL (
    TOOL_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    SCULPTURE_ID INTEGER NOT NULL,
    TOOL_NAME VARCHAR(50) NOT NULL,
    TOOL_TYPE VARCHAR(30) NOT NULL CHECK (
        TOOL_TYPE IN ('Моделювання', 'Згладжування', 'Обрізка', 'Текстурування')
    ),
    CONSTRAINT FK_TOOL_USER FOREIGN KEY (USER_ID) REFERENCES SYSTEMUSER (
        USER_ID
    ),
    CONSTRAINT FK_TOOL_SCULPTURE FOREIGN KEY (
        SCULPTURE_ID
    ) REFERENCES SCULPTURE (SCULPTURE_ID)
);

-- ===== Таблиця БазаЗнань =====
CREATE TABLE KNOWLEDGEBASE (
    BASE_ID INTEGER PRIMARY KEY,
    INFORMATION_RESOURCES TEXT NOT NULL,
    RELEVANCE DATE
);

-- ===== Таблиця Рекомендація =====
CREATE TABLE RECOMMENDATION (
    REC_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    BASE_ID INTEGER NOT NULL,
    REC_TYPE VARCHAR(30) NOT NULL CHECK (
        REC_TYPE IN ('Харчування', 'Режим праці')
    ),
    DESCRIPTION TEXT NOT NULL,
    DATE_OF_CREATION DATE NOT NULL,
    CONSTRAINT FK_REC_USER FOREIGN KEY (USER_ID) REFERENCES SYSTEMUSER (
        USER_ID
    ),
    CONSTRAINT FK_REC_BASE FOREIGN KEY (BASE_ID) REFERENCES KNOWLEDGEBASE (
        BASE_ID
    )
);

-- ===== Таблиця РекомендаціяХарчування =====
CREATE TABLE MEALRECOMMENDATION (
    REC_ID INTEGER PRIMARY KEY,
    MEAL_TIME TIME NOT NULL,
    MEAL_TYPE VARCHAR(30) NOT NULL CHECK (
        MEAL_TYPE IN ('Сніданок', 'Обід', 'Вечеря', 'Перекус')
    ),
    CALORIES INTEGER CHECK (CALORIES > 0),
    CONSTRAINT FK_RECFOOD_REC FOREIGN KEY (REC_ID) REFERENCES RECOMMENDATION (
        REC_ID
    )
);

-- ===== Таблиця РекомендаціяРежиму =====
CREATE TABLE MODERECOMMENDATION (
    REC_ID INTEGER PRIMARY KEY,
    START_TIME TIME NOT NULL,
    DURATION INTEGER NOT NULL CHECK (DURATION > 0),
    BREAK_TIME INTEGER NOT NULL CHECK (BREAK_TIME >= 0),
    CONSTRAINT FK_RECMODE_REC FOREIGN KEY (REC_ID) REFERENCES RECOMMENDATION (
        REC_ID
    )
);
