name: Javascript Code Linter
on:
  push:
    branches:
      - main # Зазвичай використовують головну гілку для перевірки

jobs:
  JavascriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code in Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Рекомендована версія

    - name: Install Biome Linter
      # Biomejs (замість @bicmejs/biome у застарілому прикладі)
      run: npm install --global @biomejs/biome

    - name: Validate all js-files
      # Припускаємо, що файл ProgramCode.js знаходиться у корені.
      # Використовуємо 'check' для перевірки на відповідність нормам.
      run: biome check ProgramCode.js
