name: JavaScript Code Linter

on:
  push:
    branches:
      - main  # або твоя гілка, якщо лабораторна у власній гілці

jobs:
  JavascriptCodeLinter:
    name: Перевірка якості JS-коду
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v4

      - name: Install Biome (JavaScript Linter)
        run: |
          npm install --save-dev --save-exact @biomejs/biome

      - name: Validate JS File
        run: |
          npx @biomejs/biome check ProgramCodeModified.js
